version: '2'
services:
    db:
        container_name: test_db
        image: cartertsai/postgres:9.5.1
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - POSTGRES_DB=test_db
        ports:
            - "5432:5432"
        restart: always
        logging:
            driver: "json-file"
        network_mode: "bridge"
