version: '2'
services:
    db:
        image: cartertsai/postgres:9.5.1
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=testtest
            - POSTGRES_DB=mrbs
        ports:
            - "5432:5432"
        restart: always
        logging:
            driver: "json-file"
